---
- name: Install WebServer
  hosts: WebServer
  #remote_user: root
  remote_user: ec2-user
  become: yes

  roles:
    - common
    - nginx

- name: Install DB Sevrer
  hosts: DBServer
  #remote_user: root
  remote_user: ec2-user
  become: yes

  roles:
    - mariadb
