---
- name: Install WebServer
  hosts: tag_Name_MgdNode_WebServer
  #remote_user: root
  remote_user: ec2-user
  become: yes

  roles:
    - common
    - nginx

- name: Install DB Sevrer
  hosts: tag_Name_MgdNode_DBServer
  #remote_user: root
  remote_user: ec2-user
  become: yes

  roles:
    - mariadb
